# Site
repository: Bensley5662/Bensley5662.github.io
favicon: 

# Content configuration version
version: 2

# Personal info
name: Tom Bensley
title: Writer, Film Critic
email: tom.bensley56@gmail.com
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
# Social links
twitter_username: @TomAliceBensley
github_username:  Bensley5662
# dribbble_username:
facebook_username: thom.bensley
# flickr_username:
# instagram_username: jameswgrant
linkedin_username: tom-bensley-475886212/
# pinterest_username:
# youtube_username:
# googleplus_username:
# orcid_username: 0000-0002-4085-9114

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpeg
about_content: |
  As far back as I can remember, I always wanted to be a writer. I never really had any other
  plans. As a kid I was writing imitations of the Goosebumps books I was reading and as soon as I'd finished 
  my creative writing degree at University I was lending my barely developed skills to anyone who would take
  me. It's a lifelong obsession with crafting a good sentence, on any subject, for anyone who needs it.
  Fortunately my skills have developed a lot since those early freelance days, and it's because every day I
  could since I wrapped my eight-year-old hand around a pencil, I haven't stopped writing. 

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Audible
        link: Audible.de
        # link_text: boringcompany.com
        sub_title: Working Student
        caption: 2019 - 2021
        #quote: >
        #  Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            

      - layout: right
        title: Hunter and Bligh
        link: https://www.hunterandbligh.com.au/author/tom-bensley/
         # link_text: boringcompany.com
        sub_title: Film Critic, Feature Writer
        caption: 2017 - 2019
        #quote: >
        #  Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            

      - layout: left
        title: The Plus Ones
        link: https://theplusones.com/melbourne/tag/film-review/
        # link_text: boringcompany.com
        sub_title: Film Specialist
        caption: 2015 - 2018
          #quote: >
          #  Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
                 

      - layout: right
        title: Theatre People AU
        link: https://www.theatrepeople.com.au/
        # link_text: boringcompany.com
        sub_title: Theatre reviewer
        caption: 2013 - 2015
          #quote: >
          #  Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
                
         
         

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Freie UniversitÃ¤t Berlin
        caption: 2018 - 2021
        sub_title: Master's degree in Literature
        quote: >
          110/110 cum laude
        # description: | # this will include new lines to allow paragraphs
         # During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

         # I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

      - layout: top-middle
        title: Deakin University, Melbourne
        caption: 2010 - 2013
        sub_title: Bachelor's Degree (Honours) Creative Writing
        quote: >
             103/110 
        # description: | # this will include new lines to allow paragraphs
        #  During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

        #  I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: Other Publications
    layout: text
    content: | # this will include new lines to allow paragraphs
       
  - title: Conferences
    layout: text
    content: | # this will include new lines to allow paragraphs
        

  - title: Awards
    layout: text
    content: | # this will include new lines to allow paragraphs
        

  - title: Various interests
    layout: text
    content: | # this will include new lines to allow paragraphs
        
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
